export const GET_ALL_PHOTOS_START = 'GET_ALL_PHOTOS_START'
export const GET_ALL_PHOTOS_SUCCES = 'GET_ALL_PHOTOS_SUCCES'
export const GET_ALL_PHOTOS_FAILURE = 'GET_ALL_PHOTOS_FAILURE'

export const GET_PHOTO_BY_ID_START = 'GET_PHOTO_BY_ID_START'
export const GET_PHOTO_BY_ID_SUCCES = 'GET_PHOTO_BY_ID_SUCCES'
export const GET_PHOTO_BY_ID_FAILURE = 'GET_PHOTO_BY_ID_FAILURE'

export const FIND_PHOTO_START = 'FIND_PHOTO_START'
export const FIND_PHOTO_SUCCES = 'FIND_PHOTO_SUCCES'
export const FIND_PHOTO_FAILURE = 'FIND_PHOTO_FAILURE'

export const FIND_BY_TAG = 'FIND_BY_TAG'

// export const DOWNLOAD_PHOTO_START = 'DOWNLOAD_PHOTO_START'
// export const DOWNLOAD_PHOTO_SUCCES = 'DOWNLOAD_PHOTO_SUCCES'
// export const DOWNLOAD_PHOTO_FAILURE = 'DOWNLOAD_PHOTO_FAILURE'